In [1]:
import numpy as np

### Element-wise multiplication of matrix

In [4]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(np.multiply(a,b))

print(a*b)




[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


## Element-wise multiplication of matrix is COMMUNATIVE, Matrix multiplication IS NOT

In [3]:
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [7]:
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1], [1], [0]])

In [5]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [ ]:
# def forward_prop(X, y):
    
#     while X != y:
#         return forward_prop(sigmoid(X), y)

In [9]:
#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

In [11]:


#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))


for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    D = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = D * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

print(output)

[[0.97690121]
 [0.97012374]
 [0.03978443]]
