In [118]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


import keras
from keras.models import Sequential
from keras.layers import Dense

In [119]:
diabetes = pd.read_csv('../data/diabetes.csv')
diabetes.head()
# print(diabetes.DESCR)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [120]:
X = diabetes.loc[:, 'Pregnancies':'Age']
y = pd.DataFrame(data=diabetes["Outcome"], columns=["Outcome"])
y.head()

Outcome
0        1
1        0
2        1
3        0
4        1

In [121]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [122]:
# Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/Users/natepill/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/natepill/anaconda3/lib/python3.7/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """


In [123]:
# Initialize Classifier Model
classifier = Sequential()

In [124]:

# Add input and output
classifier.add(Dense(activation='sigmoid', input_dim=8, units=1, kernel_initializer="uniform"))
# Compile the model
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [125]:
# Fit the model
classifier.fit(X_train, y_train, batch_size = 1, epochs=100)

Epoch 1/100
576/576 [==============================] - 1s 2ms/step - loss: 0.6366 - acc: 0.7066
Epoch 2/100
576/576 [==============================] - 0s 774us/step - loss: 0.5706 - acc: 0.7587
Epoch 3/100
576/576 [==============================] - 0s 851us/step - loss: 0.5387 - acc: 0.7483
Epoch 4/100
576/576 [==============================] - 0s 798us/step - loss: 0.5207 - acc: 0.7587
Epoch 5/100
576/576 [==============================] - 0s 793us/step - loss: 0.5094 - acc: 0.7587
Epoch 6/100
576/576 [==============================] - 0s 822us/step - loss: 0.5024 - acc: 0.7622
Epoch 7/100
576/576 [==============================] - 0s 844us/step - loss: 0.4974 - acc: 0.7708
Epoch 8/100
576/576 [==============================] - 0s 775us/step - loss: 0.4939 - acc: 0.7674
Epoch 9/100
576/576 [==============================] - 0s 795us/step - loss: 0.4917 - acc: 0.7691
Epoch 10/100
576/576 [==============================] - 1s 963us/step - loss: 0.4899 - acc: 0.7778
Epoch 11/100
576/576 

576/576 [==============================] - 0s 748us/step - loss: 0.4841 - acc: 0.7656
Epoch 84/100
576/576 [==============================] - 0s 748us/step - loss: 0.4841 - acc: 0.7604
Epoch 85/100
576/576 [==============================] - 1s 882us/step - loss: 0.4843 - acc: 0.7691
Epoch 86/100
576/576 [==============================] - 1s 895us/step - loss: 0.4841 - acc: 0.7656
Epoch 87/100
576/576 [==============================] - 0s 787us/step - loss: 0.4842 - acc: 0.7656 0s - loss: 0.4858 - acc: 0.767
Epoch 88/100
576/576 [==============================] - 0s 759us/step - loss: 0.4841 - acc: 0.7639
Epoch 89/100
576/576 [==============================] - 1s 871us/step - loss: 0.4843 - acc: 0.7639
Epoch 90/100
576/576 [==============================] - 0s 746us/step - loss: 0.4843 - acc: 0.7656
Epoch 91/100
576/576 [==============================] - 0s 854us/step - loss: 0.4842 - acc: 0.7708
Epoch 92/100
576/576 [==============================] - 0s 785us/step - loss: 0.4846 - acc:

In [126]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) # Compares each value to 0.5 threshold and replaces with bool
y_pred

# y_pred

array([[ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [

In [127]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [128]:
cm

array([[117,  13],
       [ 26,  36]])

### Logistic Regression Classification, traditional ML

In [113]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=0, solver='liblinear', multi_class='ovr').fit(X_train, y_train)

/Users/natepill/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [114]:
y_pred = lr.predict(X_test)

In [115]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [116]:
cm

array([[118,  12],
       [ 26,  36]])